controllers:
    resource: ../src/Controller/
    type: attribute
accueil:
    path: /
    controller: App\Controller\HomeController::index

# helloName:
#     path: /hello/{name}
#     controller: App\Controller\HelloController::helloName
